[project]
name = "python-server-config"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.123.10",
    "uvicorn[standard]>=0.38.0",
    "gunicorn>=22.0.0",
    "asyncpg>=0.31.0",
    "sqlalchemy[asyncio]>=2.0.44",
    "httpx>=0.28.1",
    "bcrypt>=4.0.0"
]